### ISSUE TITLE
Compilation/NameSpace Problem

### ISSUE THREAD

**Issue by karfam** [EosBandi/OverlayControlPlugin#1]
Hello
I am trying to compile your map rectangle drawing example but having problem due to references.

IGraphic is part of System?

![1](https://github.com/EosBandi/OverlayControlPlugin/assets/15799659/116ed898-6acd-4c19-8ac2-b854cd026ffa)

![2](https://github.com/EosBandi/OverlayControlPlugin/assets/15799659/bd633914-bc60-436c-baa6-3d9414131b16)

**Comment by EosBandi** [comment]
Remove and add again the nuget package system.drawing.common v4.7.2

**Comment by karfam** [comment]
Thank you very much for the reply. That fixed the problem. 
The truth is that I have tried your solution beforehand but maybe needed a restart of Visual Studio.

Is there an reference of Host.FDGMapControl ?
I try to zoom the map with a plugin but I cant find a zoom function.

**Comment by EosBandi** [comment]
Look up what UI element can change the zoom of the FDGMapControl and check what does that control's event does.....

**Comment by karfam** [comment]
double zoomlevel = 12.0;
Host.FDGMapControl.Zoom = zoomlevel;

Just for anyone looking the same :)
